DROP DATABASE IF EXISTS fec_searchbar;

CREATE DATABASE fec_searchbar;

USE fec_searchbar;

CREATE TABLE history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  searchItem TEXT
);

INSERT INTO history (searchItem) VALUES ('desk');
INSERT INTO history (searchItem) VALUES ('kitchen');
INSERT INTO history (searchItem) VALUES ('outdoor');
INSERT INTO history (searchItem) VALUES ('Where is Sweden?');
INSERT INTO history (searchItem) VALUES ('meatballs');

CREATE TABLE products (
  id INT PRIMARY KEY,
  real_name TEXT,
  simple_name TEXT,
  category TEXT,
  description TEXT,
  image_address TEXT
);

INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (1,  'ANTILOP'             , 'antilop'             , 'chair'   , 'High Chair with tray'                , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/001.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (2,  'TOBIAS'              , 'tobias'              , 'chair'   , 'Chair'                               , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/002.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (3,  'HAVSTEN'             , 'havsten'             , 'chair'   , 'Chair, indoor/outdoor'               , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/003.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (4,  'GLENN'               , 'glenn'               , 'chair'   , 'Bar Stool'                           , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/004.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (5,  'FRANKLIN'            , 'franklin'            , 'chair'   , 'Bar Stool with backrest'             , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/005.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (6,  'JULES'               , 'jules'               , 'chair'   , 'Children''s Desk Chair'              , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/006.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (7,  'ÖRFJÄLL'             , 'orfjall'             , 'chair'   , 'Swivel chair'                        , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/007.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (8,  'GRÖNADAL'            , 'gronadal'            , 'chair'   , 'Rocking chair'                       , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/008.png'); 
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (9,  'VÅGSBERG / SPORREN'  , 'vagsberg / sporren'  , 'chair'   , 'Armchair underframe'                 , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/009.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (10, 'DIETMAR'             , 'dietmar'             , 'chair'   , 'High Chair Tray'                     , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/010.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (11, 'LANGUR'              , 'langur'              , 'chair'   , 'Swivel chair'                        , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/011.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (12, 'JOKKMOKK'            , 'jokkmokk'            , 'chair'   , 'Table and 4 Chairs'                  , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/012.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (13, 'STEFAN'              , 'stefan'              , 'chair'   , 'Chair'                               , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/013.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (14, 'BALTSAR'             , 'baltsar'             , 'chair'   , 'Chair'                               , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/014.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (15, 'HARRY'               , 'harry'               , 'chair'   , 'Chair'                               , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/015.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (16, 'MARIUS'              , 'marius'              , 'chair'   , 'Stool'                               , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/016.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (17, 'MARTIN'              , 'martin'              , 'chair'   , 'Chair'                               , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/017.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (18, 'TROLLBERGET'         , 'trollberget'         , 'chair'   , 'Sitting/Standing support'            , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/018.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (19, 'KOLON'               , 'kolon'               , 'chair'   , 'Floor Protector'                     , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/019.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (20, 'MALINDA'             , 'malinda'             , 'chair'   , 'Chair pad'                           , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/020.png');

INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (21, 'GONATT'              , 'gonatt'              , 'bed'     , 'Crib'                                , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/021.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (22, 'NORDLI'              , 'nordli'              , 'bed'     , 'Bed with headboard and storage'      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/022.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (23, 'SAGSTUA'             , 'sagstua'             , 'bed'     , 'Bed frame'                           , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/023.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (24, 'GODFJORD'            , 'godfjord'            , 'bed'     , 'Bed frame'                           , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/024.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (25, 'SONGESAND'           , 'songesand'           , 'bed'     , 'Bed frame with 4 storage boxes'      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/025.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (26, 'DELAKTIG'            , 'delaktig'            , 'bed'     , 'Bed frame with headboard&side tables', 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/026.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (27, 'HEMNES'              , 'hemnes'              , 'bed'     , 'Bed frame with 4 storage boxes'      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/027.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (28, 'ESPEVÄR'             , 'espevar'             , 'bed'     , 'Divan bed'                           , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/028.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (29, 'UTÅKER'              , 'utaker'              , 'bed'     , 'Stackable bed with two mattresses'   , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/029.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (30, 'KVALFJORD'           , 'kvalfjord'           , 'bed'     , 'Bed frame'                           , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/030.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (31, 'NEIDEN'              , 'neiden'              , 'bed'     , 'Bed frame'                           , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/031.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (32, 'HEMMAHOS'            , 'hemmahos'            , 'bed'     , 'Children''s tent'                    , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/032.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (33, 'LÖVA'                , 'lova'                , 'bed'     , 'Bed canopy'                          , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/033.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (34, 'MINNEN'              , 'minnen'              , 'bed'     , 'Ext bed frame with slatted bed base' , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/034.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (35, 'SLÄKT'               , 'slakt'               , 'bed'     , 'Bed frame w/storage and slatted base', 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/035.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (36, 'VITVAL'              , 'vitval'              , 'bed'     , 'Lofted bed frame with desk top'      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/036.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (37, 'TUFFING'             , 'tuffing'             , 'bed'     , 'Bunk bed frame'                      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/037.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (38, 'NORDDAL'             , 'norddal'             , 'bed'     , 'Bunk bed frame'                      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/038.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (39, 'MYDAL'               , 'mydal'               , 'bed'     , 'Bunk bed'                            , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/039.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (40, 'ALLEMANSRÄTTEN'      , 'allemansratten'      , 'bed'     , 'Meatballs, frozen, 84% meat content' , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/040.png');

INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (41, 'HAMNSKÄR'            , 'hamnskar'            , 'bathroom', 'Bronze faucet'                       , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/041.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (42, 'LILLSVAN'            , 'lillsvan'            , 'bathroom', 'Chrome plated faucet'                , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/042.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (43, 'VOXNAN'              , 'voxnan'              , 'bathroom', 'Tall chrome faucet'                  , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/043.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (44, 'RUNSKÄR'             , 'runskar'             , 'bathroom', 'Chrome faucet, two knobs'            , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/044.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (45, 'STOCKHOLM'           , 'stockholm'           , 'bathroom', 'Mirror, walnut veneer'               , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/045.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (46, 'ISFJORDEN'           , 'isfjorden'           , 'bathroom', 'Floor mirror'                        , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/046.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (47, 'KAITUM'              , 'kaitum'              , 'bathroom', 'Mirror with built-in light'          , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/047.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (48, 'IKORNNES'            , 'ikornnes'            , 'bathroom', 'Table mirror'                        , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/048.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (49, 'GODMORGON'           , 'godmorgon'           , 'bathroom', 'Box with lid'                        , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/049.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (50, 'SAXBORGA'            , 'saxborga'            , 'bathroom', 'Jar with lid and tray, set of 5'     , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/050.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (51, 'SKÅDIS'              , 'skadis'              , 'bathroom', 'Pegboard combination'                , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/051.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (52, 'LOCKIG'              , 'lockig'              , 'bathroom', 'Children''s potty'                   , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/052.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (53, 'SAXBORGA'            , 'saxborga'            , 'bathroom', 'Storage box with mirrored lid'       , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/053.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (54, 'LÅDDAN'              , 'laddan'              , 'bathroom', '6-piece storage board set'           , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/054.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (55, 'DOPPA'               , 'doppa'               , 'bathroom', 'Bathtub mat'                         , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/055.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (56, 'TISKEN'              , 'tisken'              , 'bathroom', 'Basket with suction cup'             , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/056.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (57, 'LILLÅNGEN'           , 'lillangen'           , 'bathroom', 'Sink'                                , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/057.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (58, 'GUTVIKEN'            , 'gutviken'            , 'bathroom', 'Countertop sink'                     , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/058.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (59, 'TÖRNVIKEN'           , 'tornviken'           , 'bathroom', 'Countertop sink'                     , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/059.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (60, 'ODENSVIK'            , 'odensvik'            , 'bathroom', 'Double-bowl sink'                    , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/060.png');

INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (61, 'DUKTIG'              , 'duktig'              , 'kitchen' , 'Kids cooking set'                    , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/061.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (62, 'LILLABO'             , 'lillabo'             , 'kitchen' , 'Toy trainset'                        , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/062.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (63, 'STORABO'             , 'storabo'             , 'kitchen' , 'Play carpet'                         , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/063.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (64, 'VURM'                , 'vurm'                , 'kitchen' , 'Wine rack'                           , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/064.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (65, 'KUNGSFORS'           , 'kungsfors'           , 'kitchen' , 'Dish drainer'                        , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/065.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (66, 'ORDNING'             , 'ordning'             , 'kitchen' , 'Utensil holder'                      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/066.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (67, 'TORKAD'              , 'torkad'              , 'kitchen' , 'Paper towel holder'                  , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/067.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (68, 'IDEALISK'            , 'idealisk'            , 'kitchen' , 'Corkscrew'                           , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/068.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (69, 'JAMFORA'             , 'jamfora'             , 'kitchen' , '3-piece knife set'                   , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/069.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (70, 'ANDLIG'              , 'andlig'              , 'kitchen' , '3-piece knife set'                   , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/070.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (71, 'FÖRDUBBLA'           , 'fordubbla'           , 'kitchen' , '2-piece knife set'                   , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/071.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (72, 'FÖRSLAG'             , 'forslag'             , 'kitchen' , '3-piece knife set'                   , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/072.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (73, 'VÖRDA'               , 'vorda'               , 'kitchen' , '3-piece knife set'                   , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/073.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (74, 'DRAGON'              , 'dragon'              , 'kitchen' , '20-piece flatware set'               , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/074.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (75, 'MATLUST'             , 'matlust'             , 'kitchen' , 'Chopping board'                      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/075.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (76, 'SKYDD'               , 'skydd'               , 'kitchen' , 'Wood treatment oil, indoor use'      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/076.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (77, 'APTITLIG'            , 'aptitlig'            , 'kitchen' , 'Butcher block'                       , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/077.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (78, 'GRUNKA'              , 'grunka'              , 'kitchen' , '4-piece cooking utensil set'         , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/078.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (79, 'GUBBRÖRA'            , 'gubrora'             , 'kitchen' , 'Rubber spatula'                      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/079.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (80, 'JÄMFÖRLIG'           , 'jamforlig'           , 'kitchen' , 'Handheld whisk'                      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/080.png');

INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (81, 'KÖTTBULLAR'          , 'kottbullar'          , 'outdoor' , 'Meatballs, frozen'                   , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/081.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (82, 'FANBYN'              , 'fanbyn'              , 'outdoor' , 'Bar table and 4 bar stools'          , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/082.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (83, 'FANBYN'              , 'fanbyn'              , 'outdoor' , 'Bar stool with backrest'             , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/083.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (84, 'FRÖSÖN / DUVHOLMEN'  , 'froson / duvholmen'  , 'outdoor' , 'Seat pad, outdoor'                   , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/084.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (85, 'ÄPPLARÖ'             , 'applaro'             , 'outdoor' , 'Drop-leaf table, outdoor'            , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/085.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (86, 'ÄPPLARÖ'             , 'applaro'             , 'outdoor' , 'Bench, outdoor'                      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/086.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (87, 'ÄPPLARÖ'             , 'applaro'             , 'outdoor' , 'Chaise'                              , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/087.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (88, 'ÄPPLARÖ'             , 'applaro'             , 'outdoor' , 'Reclining chair, outdoor'            , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/088.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (89, 'FRÖSÖN / DUVHOLMEN'  , 'froson / duvholmen'  , 'outdoor' , 'Back cushion, outdoor'               , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/089.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (90, 'HAVSTEN'             , 'havsten'             , 'outdoor' , 'Loveseat, indoor/outdoor'            , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/090.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (91, 'BROMMÖ'              , 'brommo'              , 'outdoor' , 'Chaise, outdoor'                     , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/091.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (92, 'ÄPPLARÖ'             , 'applaro'             , 'outdoor' , 'Armchair, outdoor'                   , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/092.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (93, 'HÅLLÖ'               , 'hallo'               , 'outdoor' , 'Seat pad, outdoor'                   , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/093.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (94, 'SOLLERÖN'            , 'solleron'            , 'outdoor' , '3-seat modular sofa, outdoor'        , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/094.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (95, 'ÄPPLARÖ'             , 'applaron'            , 'outdoor' , 'Table and 2 benches'                 , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/095.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (96, 'TÄRNÖ'               , 'tarno'               , 'outdoor' , 'Chair, outdoor, foldable'            , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/096.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (97, 'TOSTERÖ'             , 'tostero'             , 'outdoor' , 'Cover for outdoor furniture, sofa'   , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/097.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (98, 'KLÖVEN'              , 'kloven'              , 'outdoor' , '4-seat conversion set, outdoor'      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/098.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (99, 'SOLLERÖN'            , 'solleron'            , 'outdoor' , '4-seat conversion set, outdoor'      , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/099.png');
INSERT INTO products (id, real_name, simple_name, category, description, image_address) VALUES (100, 'OTTERÖN / INNERSKÄR', 'otteron / innerskar' , 'outdoor' , 'Pouffe, indoor/outdoor'              , 'https://team-meat-searchbar-images.s3.us-east-2.amazonaws.com/100.png');